---
command: config
body: |
  Modify configuration settings

  Extended usage
  config list               - List configured settings
  config set setting value  - Change setting value

  Possible Settings / Values 
  autoloot    - (on / off)
  autoprompt  - (on / off)
  autoscan    - (on / off)
  brief       - (on / off)
  minimap     - (on / off)
  combatbars  - (on / off)
  termwidth   - Number (20 to 80)

  Example
  config set autoloot on  - Turn on autoloot
